// src/vue/MasonSprite.vue
<script setup lang="ts">
import { SPRITE_ANIMATION_DEFAULTS, SpriteAnimator, toCssLength, type SpriteAnimationClip, type SpriteAnimationOptions } from '../core/index.js';
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue';

const props = withDefaults(
  defineProps<
    SpriteAnimationOptions & {
      class?: string;
    }
  >(),
  SPRITE_ANIMATION_DEFAULTS,
);

const sizeStyle = computed(() => ({
  width: toCssLength(props.width),
  height: toCssLength(props.height),
}));

const emit = defineEmits<{
  complete: [];
  frameChange: [frame: number];
}>();

const targetRef = ref<HTMLElement | HTMLCanvasElement | null>(null);
let animator: SpriteAnimator | null = null;

function createAnimator() {
  animator?.destroy();
  animator = new SpriteAnimator({
    src: props.src,
    rows: props.rows,
    cols: props.cols,
    fps: props.fps,
    loop: props.loop,
    reverse: props.reverse,
    animations: props.animations,
    width: props.width,
    height: props.height,
    autoPlay: props.autoPlay,
    renderer: props.renderer,
    onComplete: () => emit('complete'),
    onFrameChange: (frame) => emit('frameChange', frame),
  });

  if (targetRef.value) {
    animator.attach(targetRef.value);
  }
}

onMounted(createAnimator);

onBeforeUnmount(() => {
  animator?.destroy();
  animator = null;
});

watch(
  () => [
    props.src,
    props.rows,
    props.cols,
    props.fps,
    props.loop,
    props.reverse,
    props.animations,
    props.width,
    props.height,
    props.autoPlay,
    props.renderer,
  ],
  createAnimator,
);

defineExpose({
  play: () => animator?.play(),
  pause: () => animator?.pause(),
  stop: () => animator?.stop(),
  goToFrame: (frame: number) => animator?.goToFrame(frame),
  playSegment: (clip: SpriteAnimationClip) => animator?.playSegment(clip),
  playAnimation: (name: string) => animator?.playAnimation(name),
  getState: () => animator?.getState(),
});
</script>

<template>
  <canvas
    v-if="renderer === 'canvas'"
    ref="targetRef"
    :class="props.class"
    :style="sizeStyle"
  />
  <div
    v-else
    ref="targetRef"
    :class="props.class"
    role="img"
    aria-label="Mason sprite animation"
    :style="sizeStyle"
  />
</template>

// src/svelte/MasonSprite.svelte
<script lang="ts">
  import {
    SPRITE_ANIMATION_DEFAULTS,
    SpriteAnimator,
    toCssLength,
    type SpriteAnimationOptions,
  } from 'mason-sprite';

  interface Props extends SpriteAnimationOptions {
    class?: string;
  }

  let {
    src,
    rows,
    cols,
    fps = SPRITE_ANIMATION_DEFAULTS.fps,
    loop = SPRITE_ANIMATION_DEFAULTS.loop,
    reverse = SPRITE_ANIMATION_DEFAULTS.reverse,
    animations,
    width = SPRITE_ANIMATION_DEFAULTS.width,
    height = SPRITE_ANIMATION_DEFAULTS.height,
    autoPlay = SPRITE_ANIMATION_DEFAULTS.autoPlay,
    renderer = SPRITE_ANIMATION_DEFAULTS.renderer,
    onComplete,
    onFrameChange,
    class: className = '',
  }: Props = $props();

  let target = $state<HTMLElement | HTMLCanvasElement | undefined>();
  let animator = $state<SpriteAnimator | null>(null);

  $effect(() => {
    const el = target;
    if (!el) return;

    const instance = new SpriteAnimator({
      src,
      rows,
      cols,
      fps,
      loop,
      reverse,
      animations,
      width,
      height,
      autoPlay,
      renderer,
      onComplete,
      onFrameChange,
    });

    instance.attach(el);
    animator = instance;

    return () => {
      instance.destroy();
      animator = null;
    };
  });

  export function play() {
    animator?.play();
  }

  export function pause() {
    animator?.pause();
  }

  export function stop() {
    animator?.stop();
  }

  export function goToFrame(frame: number) {
    animator?.goToFrame(frame);
  }

  export function playSegment(clip: import('mason-sprite').SpriteAnimationClip) {
    animator?.playSegment(clip);
  }

  export function playAnimation(name: string) {
    animator?.playAnimation(name);
  }

  export function getState() {
    return animator?.getState();
  }
</script>

{#if renderer === 'canvas'}
  <canvas bind:this={target} class={className} style="width: {toCssLength(width)}; height: {toCssLength(height)};"></canvas>
{:else}
  <div
    bind:this={target}
    class={className}
    role="img"
    aria-label="Mason sprite animation"
    style="width: {toCssLength(width)}; height: {toCssLength(height)};"
  ></div>
{/if}
