// src/vue/Sprite.vue
<script setup lang="ts">
import { SPRITE_ANIMATION_DEFAULTS, SpriteAnimator, toCssLength, type SpriteAnimationClip, type SpriteAnimationOptions } from '../core/index.js';
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue';

const props = withDefaults(
  defineProps<
    SpriteAnimationOptions & {
      class?: string;
    }
  >(),
  SPRITE_ANIMATION_DEFAULTS,
);

const sizeStyle = computed(() => ({
  width: toCssLength(props.width),
  height: toCssLength(props.height),
}));

const emit = defineEmits<{
  complete: [];
  frameChange: [frame: number];
}>();

const targetRef = ref<HTMLElement | HTMLCanvasElement | null>(null);
let animator: SpriteAnimator | null = null;

function createAnimator() {
  animator?.destroy();
  animator = new SpriteAnimator({
    src: props.src,
    rows: props.rows,
    cols: props.cols,
    fps: props.fps,
    loop: props.loop,
    reverse: props.reverse,
    animations: props.animations,
    width: props.width,
    height: props.height,
    autoPlay: props.autoPlay,
    renderer: props.renderer,
    onComplete: () => emit('complete'),
    onFrameChange: (frame) => emit('frameChange', frame),
  });

  if (targetRef.value) {
    animator.attach(targetRef.value);
  }
}

onMounted(createAnimator);

onBeforeUnmount(() => {
  animator?.destroy();
  animator = null;
});

watch(
  () => [
    props.src,
    props.rows,
    props.cols,
    props.fps,
    props.loop,
    props.reverse,
    props.animations,
    props.width,
    props.height,
    props.autoPlay,
    props.renderer,
  ],
  createAnimator,
);

defineExpose({
  play: () => animator?.play(),
  pause: () => animator?.pause(),
  stop: () => animator?.stop(),
  goToFrame: (frame: number) => animator?.goToFrame(frame),
  playSegment: (clip: SpriteAnimationClip) => animator?.playSegment(clip),
  playAnimation: (name: string) => animator?.playAnimation(name),
  getState: () => animator?.getState(),
});
</script>

<template>
  <canvas
    v-if="renderer === 'canvas'"
    ref="targetRef"
    :class="props.class"
    :style="sizeStyle"
  />
  <div
    v-else
    ref="targetRef"
    :class="props.class"
    role="img"
    aria-label="Sprite animation"
    :style="sizeStyle"
  />
</template>

// src/react/Sprite.tsx
import type { SpriteAnimationClip, SpriteAnimationOptions } from '../core/types.js';
import { SPRITE_ANIMATION_DEFAULTS, toCssLength } from '../core/index.js';
import { forwardRef, useImperativeHandle } from 'react';
import { useSprite } from './useSprite.js';

export interface SpriteProps extends SpriteAnimationOptions {
  className?: string;
  style?: React.CSSProperties;
}

export interface SpriteHandle {
  play: () => void;
  pause: () => void;
  stop: () => void;
  goToFrame: (frame: number) => void;
  playSegment: (clip: SpriteAnimationClip) => void;
  playAnimation: (name: string) => void;
}

export const Sprite = forwardRef<SpriteHandle, SpriteProps>(function Sprite(
  { className, style, width, height, ...options },
  ref,
) {
  const { ref: targetRef, play, pause, stop, goToFrame, playSegment, playAnimation } = useSprite({
    width,
    height,
    ...options,
  });

  useImperativeHandle(ref, () => ({ play, pause, stop, goToFrame, playSegment, playAnimation }), [
    play,
    pause,
    stop,
    goToFrame,
    playSegment,
    playAnimation,
  ]);

  const sizeStyle = {
    width: toCssLength(width ?? SPRITE_ANIMATION_DEFAULTS.width),
    height: toCssLength(height ?? SPRITE_ANIMATION_DEFAULTS.height),
  };

  if (options.renderer === 'canvas') {
    return (
      <canvas
        ref={targetRef as React.RefObject<HTMLCanvasElement>}
        className={className}
        style={{ ...sizeStyle, ...style }}
      />
    );
  }

  return (
    <div
      ref={targetRef as React.RefObject<HTMLDivElement>}
      className={className}
      style={{ ...sizeStyle, ...style }}
      role="img"
      aria-label="Sprite animation"
    />
  );
});
